#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - '**/gen-codes/**'
    - '**/*.md'
    - 'dist'
    - 'licenses'
    - '**/go.mod'
    - '**/go.sum'
    - 'LICENSE'
    - 'NOTICE'
    - '.gitignore'
    - '.gitmodules'
    - '.gitattributes'
    - 'test/e2e/base/.mvn'
    # Copy from https://github.com/grandecola/bigqueue, listed in the LICENSE file
    - 'plugins/queue/mmap/queue_operation.go'

  comment: on-failure

dependency:
  files:
    - go.mod
  licenses:
    - name: github.com/ajstarks/svgo
      version: v0.0.0-20180226025133-644b8db467af
      license: CC-BY-3.0
    - name: github.com/bugsnag/osext
      version: v0.0.0-20130617224835-0dd3f918b21b
      license: Zlib
    - name: github.com/dnaeon/go-vcr
      version: v1.0.1
      license: BSD-2-Clause
    - name: github.com/globalsign/mgo
      version: v0.0.0-20181015135952-eeefdecb41b8
      license: BSD-2-Clause
    - name: github.com/glycerine/go-unsnap-stream
      version: v0.0.0-20180323001048-9f0cb55181dd
      license: MIT
    - name: github.com/gogo/protobuf
      version: v1.3.2
      licnese: BSD-3-Clause
    - name: github.com/golang/freetype
      version: v0.0.0-20170609003504-e2365dfdc4a0
      license: BSD-3-Clause-And-GPL-2
    - name: github.com/magiconair/properties
      version: v1.8.1
      license: BSD-2-Clause
    - name: github.com/mitchellh/osext
      version: v0.0.0-20151018003038-5e2d6d41470f
      license: Zlib
    - name: github.com/pascaldekloe/goe
      version: v0.1.0
      license: CC0-1.0
    - name: github.com/seccomp/libseccomp-golang
      version: v0.9.1
      license: BSD-2-Clause
    - name: github.com/shirou/gopsutil
      version: v3.21.11+incompatible
      license: BSD-3-Clause
    - name: gonum.org/v1/plot
      version: v0.0.0-20190515093506-e2840ee46a6b
      license: BSD-3-Clause
    - name: gopkg.in/check.v1
      version: v1.0.0-20200902074654-038fdea0a05b
      license: BSD-2-Clause
    - name: gopkg.in/gcfg.v1
      version: v1.2.3
      license: BSD-3-Clause
    - name: gopkg.in/inf.v0
      version: v0.9.1
      license: BSD-3-Clause
    - name: gopkg.in/tomb.v1
      version: v1.0.0-20141024135613-dd632973f1e7
      license: BSD-3-Clause